name: Secret Scanning

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python
          queries: +security-and-quality  # Asegura un análisis más detallado

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

